default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: u_innova_pdf_development

test:
  <<: *default
  database: u_innova_pdf_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_QUEUE_URL"] %>
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    url: <%= ENV["DATABASE_CACHE_URL"] %>
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    url: <%= ENV["DATABASE_CABLE_URL"] %>
    migrations_paths: db/cable_migrate
